name: Github-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build

  build-docker-compose:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker-compose up -d
      - name: Check if container db is running
        run: |
          if [ $(docker ps -qf name="db") ] then
            echo "Container db is running"
          else
            echo "Container db is NOT running"
            exit 1
          fi
      - name: Check if container app is running
        run: |
          if [ $(docker ps -qf name="app") ] then
            echo "Container app is running"
          else
            echo "Container app is NOT running"
            exit 1
          fi
      - name: Stop containers
        if: always()
        run: docker-compose down